### PR TITLE
[fix] Bug in searching of group roles

### PR DESCRIPTION
**Pull request by mdlama**
Was filtering on incorrect variable (id) - changed to correct (name)

### CODE REVIEW

**Comment by anthonyfuentes** [comment]
Hello Drew. Can you provide a bit of context to frame this change? Was there a particular chain of execution you followed to the line you changed?

**Comment by mdlama** [comment]
Sure.  I was looking for code that retrieved the user ids for members in a group with a specific role.  I found this function in the framework code, but noticed that the query was checking if `$role` (a string) was equal to `id`, which didn't make any sense to me.  Changing it to `name` makes the code work (at least according to my expectations).

**Comment by hubzero-admin** [comment]
Hello Drew. Can you provide a set of steps for recreating the issue/ seeing the change this update affects?

**Comment by mdlama** [comment]
Ah, good call, hubzero-admin.  Your prompt had me look into the code to see where this is used.  It is only used in Plugins/Groups/Members [here](https://github.com/hubzero/hubzero-cms/blob/d8a48a141b43e0e8a6ab46fb954bbe13f22061e1/core/plugins/groups/members/members.php#L271).  Based on the code, it looks like it indeed DOES accept an id for the role and not a string.  

This happens when filtering on member roles in a group's member area.  Once a member role is clicked, the ID of the role is stored in role_filter (example URL:  https://192.168.33.10/groups/myregulargroup/members?role_filter=5)  This is then sent to the `search_roles` method (`\Hubzero\User\Group\Helper::search_roles($group, $view->role_filter)`).  

It looks like the code is working properly and this can be closed without merge.  I went ahead and made a copy of this method anyways and am using it in a different context.  I think the thing that threw me off was the documentation header saying that role was a string combined with my own bias needing it to be a string for my use case.

Thanks,

- Drew

**Comment by datafatmunger** [comment]
Needs testing ...

**Comment by erichhuebner** [comment]
Per request "It looks like the code is working properly and this can be closed without merge."  Closing.

**Pull request closed without merging**
